### ISSUE TITLE
Board / Order API 추가 및 수정 요청

### ISSUE THREAD

**Issue by Forourhappy** [yeoboya-lunch/yeoboya-lunch-api#13]
## 기능 설명

> 추가하려는 기능에 대해 간결하게 설명해주세요

- 게시글 POST 요청과 GET 요청 시, hashTag 형식이 서로 다릅니다.
- 주문 모집 참여(/order/recruit/join)를 수정할 메서드가 없습니다.
- 개별 주문 조회 부분 문서가 잘못되어 있습니다.

## 작업 상세 내용

- [x] 게시글 API 형식 통일
- [x] 주문 모집 참여 API 추가
- [ ] API 문서 업데이트

### 게시글 등록
![image](https://github.com/yeoboya-lunch/yeoboya-lunch-api/assets/111723390/db150aa4-7d13-4378-b58b-eabc22850111)

### 게시글 단건 조회
![image](https://github.com/yeoboya-lunch/yeoboya-lunch-api/assets/111723390/2a2278b5-02c8-4d69-988a-e940ce5104b2)

### 개별 주문 조회
![image](https://github.com/yeoboya-lunch/yeoboya-lunch-api/assets/111723390/5f478dea-2b22-4a17-838e-98f108416f6a)

**Comment by khjzzm** [comment]
**점심 주문 모집 참가**
~~~
curl --location 'http://localhost:8080/order/recruit/join' \
--data-raw '{
    "orderId":13,
    "email":"go@in6.com",
    "orderItems" : [
        {
            "itemName":"감자튀김",
            "orderQuantity":10
        }
    ]
}'
~~~

**점심 주문 모집 수정**
~~~
curl --location --request PATCH 'http://localhost:8080/order/recruit/join' \
--data-raw '{
    "orderId":12,
    "groupOrderId":36,
    "email":"go@in6.com",
    "orderItems" : [
        {
            "itemName":"소고기",
            "orderQuantity":12
        }
    ]
}'
~~~

**내주문내역**
~~~
curl --location 'http://localhost:8080/order/recruit/histories/join/go@in.com' \
~~~

**내모집내역**
~~~
curl --location 'http://localhost:8080/order/recruit/histories/55@55.com' \
~~~

**Comment by Forourhappy** [comment]
api 업데이트를 제외한 항목들이 해결되었기에 이 Issue는 닫도록 하겠습니다.
